### ISSUE TITLE
Reload of UI on a page results in "not found" page

### ISSUE THREAD

**Issue by mohsinbeg** [feldera/dbsp#270]
1. Navigate to Pipeline Builder
2. Create a new pipeline
3. Confirm the updated URL in the browser
4. Do a browser refresh
5. See a blank page with "not found" text. ![Screenshot 2023-06-22 at 6 40 43 PM](https://github.com/feldera/dbsp/assets/28739668/14437659-0ddb-431f-9ac4-6b67da4ea8f2)

**Comment by lalithsuresh** [comment]
Another way to reproduce this is to create a pipeline, go to "pipeline management", click edit for that pipeline, and then refresh.

**Comment by gz** [comment]
Gist of this issue has to do with nextjs routing, the problem is described here:

> This is because when you use the next/link component the href prop has the "real" URL to the page with the query parameter for the item ID set. This means that on the client (the browser), Next.js can load the right page (your product.js page) with the parameter for your data query.
> But when you load from the server, either by reloading the page or opening it in a new window, Next.js doesn't know what page to load and in this case I think it will try to find the file ./pages/new-releases/product/Plattan-2-Bluetooth.js, which of course doesn't exist.

https://stackoverflow.com/questions/54815348/nextjs-page-goes-to-404-on-refresh

which seems to be what happens in our case. This fix is to have only static url components and use `?bla=foo` for passing 'dynamic query parameters' such as pipeline Ids etc. So I'll change to that model for URLs.

If we want to go back to nicer URLs like `/view/${pipelineid}` we need to support this with a backend that understands these urls (right now all our backend does is shipping static assembled HTML so it won't work)
