### ISSUE TITLE
UI error navigating to Pipeline Builder while "SecOps demo" SQL was compiling

### ISSUE THREAD

**Issue by mohsinbeg** [feldera/dbsp#325]
1. Do latest pull
    - `~/r/f/dbsp (main)> git log --oneline -n1
ebed7d09 (HEAD -> main, origin/main, origin/HEAD) [sql] Implement multiple string manipulation functions (#321)`
2. Deploy new containers
    - `~/r/f/dbsp (main)> cat ./deploy/docker-compose.yml | docker compose -f - --profile demo up --pull always --renew-anon-volumes --force-recreate`
3. Navigate to **Existing Programs** to confirm the "SecOps demo" is in `Building Pipeline` status
4. Navigate to **Pipeline Builder** and the below error is raised.
<kbd> ![Screenshot 2023-07-07 at 6 26 01 PM](https://github.com/feldera/dbsp/assets/28739668/ffa08ecb-821a-4278-bc5a-6f659c291c64) </kbd>

**Comment by gz** [comment]
Hm it *looks like* it may have used a cached version of the UI in your browser. I'm suspecting this because that JSON parsing part has been removed with the versioning update and there is no JSON parsing on this page happening anymore at all :/

I'm assuming this isn't reproducible if you do Ctrl+Shit+R? This is a bit annoying need some way to control/nuke the browser cache on updates..

**Comment by mohsinbeg** [comment]
> I'm assuming this isn't reproducible if you do Ctrl+Shit+R? Looks like we need some way to control/nuke the browser cache after updates...

Yes, I kept the browser window on purpose to test UI upgrade. Closing the issue as I am unable to reproduce after forcing a UI refresh.
