### ISSUE TITLE
Pipeline Management does not show complete details

### ISSUE THREAD

**Issue by mohsinbeg** [feldera/dbsp#388]
1. Create a SQL program
2. Go to Pipeline Builder
3. Create a pipeline by selecting the SQL program by name
4. Click "Add a new Input"
5. Select one of the entries and click Add
6. Click on Pipeline Management
7. Expand the newly created pipeline
8. Configuration shows "not set"

**Comment by gz** [comment]
The root of the issue is that the pipeline doesn't have a committed revision yet (since it never ran) and the expanded view should displays the running pipeline configuration.
I will change this so the tab only expands when there is a revision&the pipeline is running which should make it less confusing.
