### ISSUE TITLE
Diagnostics report for pipeline failures and OOMs

### ISSUE THREAD

**Issue by ryzhyk** [feldera/dbsp#80]
This issue covers the end-to-end handling of pipeline failures.

- [x] Make sure that panics in worker threads terminate the pipeline process, write something meaningful to the log, and the error gets propagated to the DB, UI, API.
  - [x] Need to do a general pass over error handling from the API, everywhere return (ideally) a code/number, message and a location (file/linenumber/maybe backtrace) (only in debug/dev mode) to the client
- [ ] Pipeline runner should make an effort to pause itself before running OOM and produce a memory profile (we already have low-level support for this). This isn't standard (typically people rely on resource limits to just kill runaway jobs), but given how easy it is to run OOM in DBSP today, I think that this feature is necessary for good user experience.
- [x] Make sure the manager is able to monitor the state of a pipeline, including on manager restart (or do we just kill pipelines when the manager shuts down in the dev form factor?)
- [x] Better connector error reporting, e.g., when a Kafka connector cannot connect to a broker, the connector produces a cryptic error ("failed to join consumer group '1685333843725', giving up after 10s"), and even this error doesn't propagate cleanly to the API or UI client.
  - [ ] Related to this, we may want to treat the above situation as a transient error and allow the pipeline to start (and later retry connector initialization)
- [x] CSV/JSON parsing errors must be reported in a meaningful way
- [x] Make sure all UI/API interactions, incl errors, are easy to observe in the log.

**Comment by lalithsuresh** [comment]
One user experience issue is that the manager logs aren't particularly informative. A guiding principle could be to have the UI feedback in case of errors also be logged on the manager logs at the INFO and ERROR levels. For example, compilation errors, accesses to deleted objects etc, database not accessible.

**Comment by ryzhyk** [comment]
> have the UI feedback
As in, responses (successes and errors) sent back to the UI by the manager must be logged?

**Comment by lalithsuresh** [comment]
Yes, but not in the sense of logging raw HTTP responses, but producing human-friendly log messages. These same messages could be bubbled to the UI too and could be part of the OpenAPI contract. That way, users can cross check what they see in the UI and API responses with the pipeline logs, and they can share the pipeline logs with us when they hit bugs.

Some examples: 

* if an object was successfully created, we can log "[INFO] Pipeline object {} successfully created".
* If we get a compilation error for a program, "[INFO] Could not compile program {// show name and ID}: " followed by the SQL query, the problematic line underlined and the error message.
* If clicking the pipeline play button fails, "[ERROR] Could not run pipeline {// show name and ID} because of {}".

In some cases, we might not want to bubble errors to the UI/API.

**Comment by ryzhyk** [comment]
This makes sense, #277 is moving in this direction.  And yes, most errors should pop up in the UI (they are already part of the HTTP response, so it should only be a matter of visualizing them).

**Comment by gz** [comment]
It would be good to have error codes (integer) for errors. Sometimes the error message we return does make sense on the manger level but in the UI you can give more clear directions on what to do about it and how to resolve since it's in the context of the UI

**Comment by ryzhyk** [comment]
I checked the parser error reporting item as done.  The remaining part of this task is now a separate issue: #453.

**Comment by ryzhyk** [comment]
Closing this. The remaining todo is now a separate issue #495
